services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile.dev
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/local/app/frontend
    profiles:
      - dev

  frontend-prod:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile.prod
    ports:
      - ${CLIENT_PORT}:3000
    env_file:
      - .env
    profiles:
      - prod

  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongo-init-replica
    environment:
      MONGO_HOST: mongo
    env_file:
      - .env
    volumes:
      - ./backend:/usr/local/app/backend
    profiles:
      - dev

  backend-prod:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.prod
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongo-init-replica
    env_file:
      - .env
    environment:
      MONGO_HOST: mongo
    profiles:
      - prod

  mongo:
    image: mongo
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--auth",
        "--keyFile",
        "/data/keyfile",
      ]
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo-key/keyfile:/data/keyfile
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

  mongo-init-replica:
    image: mongo
    depends_on:
      - mongo
    env_file:
      - .env
    command: >
      sh -c "
        echo 'Waiting for MongoDB to start...';
        sleep 10;
        echo 'Attempting to initiate replica set...';
        mongosh --host mongo --port 27017 -u ${MONGO_USER} -p ${MONGO_PASSWORD} --authenticationDatabase admin --eval 'rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"mongo:27017\" }] });'
      "

volumes:
  mongo-data:

networks:
  default:
