
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile.dev
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/local/app/frontend
    profiles:
      - dev

  frontend-prod:
    build:
      context: .
      dockerfile: ./frontend/docker/Dockerfile.prod
    ports:
      - ${CLIENT_PORT}:3000
    env_file:
      - .env
    profiles:
      - prod

  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
    env_file:
      - .env
    volumes:
      - ./backend:/usr/local/app/backend
    profiles:
      - dev

  backend-prod:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile.prod
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGO_HOST: mongo
    profiles:
      - prod

  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo-data:/data/db # Ensure this volume is created externally and at the correct path
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

volumes:
  mongo-data:
  
networks:
  default: