name: Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lambda:
    name: Deploy LAMBDA Inventory
    runs-on: eee-ims
    steps:
      - name: clone repo and update
        run: |
          cd /home/ubuntu/lambda-inventory
          git pull
          docker compose --profile prod up --build -d